image: Ubuntu

stack: jdk 11

branches:
  only:
  - main

install:
  - chmod +x gradlew
  - java -jar ./artifacts/app-ibank-build-for-testers.jar &



build: off

build_script:
  - ./gradlew test -Dselenide.headless=true --info






